name: GitHub Pages Deployment
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04
    steps:
      - name: Download Repository
        uses: actions/checkout@v1

      - name: Install Dependencies
        run: npm install

      - name: Build Website
        run: npm run export

      - name: Add CNAME and Robots.txt
        run: mv robots.txt CNAME __sapper__/export

      - name: Upload To GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./__sapper__/export
