name: GitHub Pages Deployment
on: push

jobs:
    build:
        runs-on: ubuntu-18.04
        uses: webfactory/ssh-agent@v0.1.1
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        - name: test env
        run: node -v
        